name: Hello Word Workflow # nombre del workflow
on: workflow_dispatch #el tipo de evento


jobs: #aqui es donde ordenamos los jobs
    hello:
        runs-on: ubuntu-latest
        steps: 
            - name: Hello Word
              run: echo "Hello Word"


    test:
        runs-on: ubuntu-latest #maquina virtual
        needs: hello #dependencia
        if: ${{ success() }}
        steps: 
            - name: Ejecucion de test
              run: echo "Running tests ..."


    deploy:
        runs-on: self-hosted
        needs: test #dependencia del job test
        if: ${{ success() }}
        steps:
            - name: Deployment
              run: echo "Deploying application..."
